-- MediFlow E-Channeling production-oriented MySQL schema (starter)
CREATE DATABASE IF NOT EXISTS mediflow CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE mediflow;
CREATE TABLE users(id BIGINT PRIMARY KEY AUTO_INCREMENT,role ENUM('admin','doctor','patient') NOT NULL,username VARCHAR(80) UNIQUE NOT NULL,password_hash VARCHAR(255) NOT NULL,name VARCHAR(150) NOT NULL,phone VARCHAR(20),email VARCHAR(150),active BOOLEAN DEFAULT TRUE,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE specialties(id BIGINT PRIMARY KEY AUTO_INCREMENT,name VARCHAR(120) UNIQUE NOT NULL);
CREATE TABLE doctors(id BIGINT PRIMARY KEY AUTO_INCREMENT,user_id BIGINT NOT NULL,specialty_id BIGINT,slmc_reg_no VARCHAR(40) UNIQUE NOT NULL,consultation_fee DECIMAL(10,2) NOT NULL,experience_years INT DEFAULT 0,bio TEXT,photo_url TEXT,available BOOLEAN DEFAULT TRUE,FOREIGN KEY(user_id) REFERENCES users(id),FOREIGN KEY(specialty_id) REFERENCES specialties(id));
CREATE TABLE patients(id BIGINT PRIMARY KEY AUTO_INCREMENT,user_id BIGINT NOT NULL,nic VARCHAR(20) UNIQUE NULL,dob DATE NOT NULL,gender VARCHAR(20) NOT NULL,address VARCHAR(255),emergency_name VARCHAR(150),emergency_phone VARCHAR(20),FOREIGN KEY(user_id) REFERENCES users(id));
CREATE TABLE doctor_schedules(id BIGINT PRIMARY KEY AUTO_INCREMENT,doctor_id BIGINT NOT NULL,schedule_date DATE NOT NULL,working_from TIME NOT NULL,working_to TIME NOT NULL,available BOOLEAN DEFAULT TRUE,UNIQUE KEY uq_doctor_date(doctor_id,schedule_date),FOREIGN KEY(doctor_id) REFERENCES doctors(id));
CREATE TABLE doctor_slots(id BIGINT PRIMARY KEY AUTO_INCREMENT,doctor_schedule_id BIGINT NOT NULL,slot_time TIME NOT NULL,UNIQUE KEY uq_schedule_slot(doctor_schedule_id,slot_time),FOREIGN KEY(doctor_schedule_id) REFERENCES doctor_schedules(id));
CREATE TABLE doctor_leaves(id BIGINT PRIMARY KEY AUTO_INCREMENT,doctor_id BIGINT NOT NULL,leave_date DATE NOT NULL,reason VARCHAR(255),FOREIGN KEY(doctor_id) REFERENCES doctors(id));
CREATE TABLE appointments(id BIGINT PRIMARY KEY AUTO_INCREMENT,patient_id BIGINT NULL,doctor_id BIGINT NOT NULL,date DATE NOT NULL,time TIME NOT NULL,queue_no INT,status ENUM('pending','confirmed','completed','cancelled','no_show') DEFAULT 'pending',reason TEXT,payment_method VARCHAR(40),payment_ref VARCHAR(120),payment_status ENUM('unpaid','pending_verification','paid','refunded') DEFAULT 'unpaid',amount DECIMAL(10,2) NOT NULL,cancel_reason VARCHAR(255),created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY(patient_id) REFERENCES patients(id),FOREIGN KEY(doctor_id) REFERENCES doctors(id),INDEX idx_slot(doctor_id,date,time));
CREATE TABLE payments(id BIGINT PRIMARY KEY AUTO_INCREMENT,appointment_id BIGINT NOT NULL,patient_id BIGINT NULL,patient_name VARCHAR(150),patient_phone VARCHAR(20),amount DECIMAL(10,2) NOT NULL,method VARCHAR(40),reference VARCHAR(120),proof_data LONGTEXT, rejection_reason VARCHAR(255),verified_by BIGINT NULL,verified_at TIMESTAMP NULL, cash_received DECIMAL(10,2) DEFAULT NULL,balance_returned DECIMAL(10,2) DEFAULT 0,status VARCHAR(30),paid_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY(appointment_id) REFERENCES appointments(id),FOREIGN KEY(patient_id) REFERENCES patients(id));
CREATE TABLE notifications(id BIGINT PRIMARY KEY AUTO_INCREMENT,user_id BIGINT NOT NULL,title VARCHAR(180),message TEXT,is_read BOOLEAN DEFAULT FALSE,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY(user_id) REFERENCES users(id));
CREATE TABLE reviews(id BIGINT PRIMARY KEY AUTO_INCREMENT,appointment_id BIGINT NOT NULL,doctor_id BIGINT NOT NULL,patient_id BIGINT NOT NULL,rating TINYINT NOT NULL,review_text TEXT,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY(appointment_id) REFERENCES appointments(id),FOREIGN KEY(doctor_id) REFERENCES doctors(id),FOREIGN KEY(patient_id) REFERENCES patients(id));
CREATE TABLE audit_logs(id BIGINT PRIMARY KEY AUTO_INCREMENT,actor_user_id BIGINT,action VARCHAR(180) NOT NULL,target_id VARCHAR(80),created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY(actor_user_id) REFERENCES users(id));

-- v3 billing / invoice / refund architecture
CREATE TABLE IF NOT EXISTS invoices(id BIGINT PRIMARY KEY AUTO_INCREMENT,invoice_no VARCHAR(50) UNIQUE NOT NULL,appointment_id BIGINT NOT NULL,patient_id BIGINT NULL,patient_name VARCHAR(150),patient_phone VARCHAR(20),status VARCHAR(30) DEFAULT 'issued',currency CHAR(3) DEFAULT 'LKR',subtotal DECIMAL(10,2) NOT NULL,fees DECIMAL(10,2) DEFAULT 0,tax DECIMAL(10,2) DEFAULT 0,discount DECIMAL(10,2) DEFAULT 0,total DECIMAL(10,2) NOT NULL,amount_received DECIMAL(10,2) DEFAULT 0,balance DECIMAL(10,2) DEFAULT 0,issued_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY(appointment_id) REFERENCES appointments(id),FOREIGN KEY(patient_id) REFERENCES patients(id));
CREATE TABLE IF NOT EXISTS invoice_items(id BIGINT PRIMARY KEY AUTO_INCREMENT,invoice_id BIGINT NOT NULL,description VARCHAR(255) NOT NULL,qty DECIMAL(10,2) DEFAULT 1,unit_price DECIMAL(10,2) NOT NULL,line_total DECIMAL(10,2) NOT NULL,FOREIGN KEY(invoice_id) REFERENCES invoices(id));
CREATE TABLE IF NOT EXISTS refunds(id BIGINT PRIMARY KEY AUTO_INCREMENT,payment_id BIGINT,appointment_id BIGINT NOT NULL,patient_id BIGINT NULL,patient_name VARCHAR(150),amount DECIMAL(10,2) NOT NULL,reason VARCHAR(255),status ENUM('requested','approved','processed','rejected') DEFAULT 'requested',requested_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,processed_at TIMESTAMP NULL,FOREIGN KEY(appointment_id) REFERENCES appointments(id),FOREIGN KEY(patient_id) REFERENCES patients(id));
ALTER TABLE users ADD UNIQUE KEY uq_users_email(email);
